import tailwindcss from '@tailwindcss/vite';
import { tanstackStart } from '@tanstack/react-start/plugin/vite';
import { defineConfig, PluginOption } from 'vite';
import tsConfigPaths from 'vite-tsconfig-paths';
import viteReact from '@vitejs/plugin-react';
import path from 'path';

const astGrepShim = path.resolve(__dirname, 'src/shims/ast-grep-napi.ts');

export default defineConfig({
  server: {
    port: 3000,
  },
  build: {
    target: 'esnext',
    rollupOptions: {
      external: [
        'node:async_hooks',
        'cloudflare:workers',
        'tanstack-start-manifest:v',
        'tanstack-start-route-tree:v',
        'tanstack-start-server-fn-manifest:v',
      ],
    },
  },
  plugins: [
    tailwindcss() as PluginOption,
    tsConfigPaths({
      projects: ['./tsconfig.json'],
    }),
    tanstackStart({
      customViteReactPlugin: true,
      target: 'cloudflare-module',
      tsr: {
        routeTreeFileHeader: [
          '/** biome-ignore-all lint/suspicious/noExplicitAny: code generated by @tanstack/react-start */',
        ],
        quoteStyle: 'double',
      },
    }),
    viteReact(),
  ],
  resolve: {
    alias: {
      '@ast-grep/napi': astGrepShim,
    },
  },
});
