import tailwindcss from '@tailwindcss/vite';
import { tanstackStart } from '@tanstack/react-start/plugin/vite';
import { defineConfig, PluginOption } from 'vite';
import tsConfigPaths from 'vite-tsconfig-paths';
import { cloudflareWorkersDevEnvironmentShim } from 'alchemy/cloudflare';
import { cloudflare } from '@cloudflare/vite-plugin';
import viteReact from '@vitejs/plugin-react';
import path from 'path';

const astGrepShim = path.resolve(__dirname, 'src/shims/ast-grep-napi.ts');

export default defineConfig({
  server: {
    port: 3000,
  },
  build: {
    target: 'esnext',
    rollupOptions: {
      external: ['node:async_hooks', 'cloudflare:workers'],
    },
  },
  plugins: [
    tailwindcss() as PluginOption,
    cloudflareWorkersDevEnvironmentShim(),
    // Add Cloudflare plugin for D1 bindings support
    cloudflare({
      persistState: process.env.ALCHEMY_CLOUDFLARE_PERSIST_PATH
        ? {
            path: process.env.ALCHEMY_CLOUDFLARE_PERSIST_PATH,
          }
        : undefined,
    }),
    tsConfigPaths({
      projects: ['./tsconfig.json'],
    }),
    tanstackStart({
      customViteReactPlugin: true,
      target: 'cloudflare-module',
      tsr: {
        routeTreeFileHeader: [
          '/** biome-ignore-all lint/suspicious/noExplicitAny: code generated by @tanstack/react-start */',
        ],
        quoteStyle: 'double',
      },
    }),
    viteReact(),
  ],
  resolve: {
    alias: {
      '@ast-grep/napi': astGrepShim,
    },
  },
});
